### ISSUE TITLE
Dialog 에서 발생하는 error

### ISSUE THREAD

**Issue by LeeJeongHwi** [ITs-smu-Team/its-core-android#5]
```
E/WindowManager: android.view.WindowLeaked: Activity com.example.mlkit_pose.kotlin.CameraXLivePreviewActivity has leaked window DecorView@bfb4488[CameraXLivePreviewActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:763)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:747)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:427)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:116)
        at android.app.Dialog.show(Dialog.java:424)
        at com.example.mlkit_pose.kotlin.CameraXLivePreviewActivity.giveup_Button_Click(CameraXLivePreviewActivity.kt:204)
        at com.example.mlkit_pose.kotlin.CameraXLivePreviewActivity.onBackPressed(CameraXLivePreviewActivity.kt:209)
        at android.app.Activity.onKeyUp(Activity.java:3803)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2872)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4109)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:431)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6208)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6076)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5514)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5571)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5537)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5545)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5518)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5571)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5537)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5706)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5545)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5763)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5518)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5571)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5537)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5545)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5518)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5571)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5537)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5739)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5897)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3220)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2755)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2746)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3197)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7867)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

다음과 같은 로그가 발생함
왜 발생하는지는 모르겠음;

**Comment by LeeJeongHwi** [comment]
`dialog.dismiss()` 하기 전에 이미 `finish()`를 해버려가지고 문제가 발생한 현상, 나머지도 수정해야할듯
